services:
  pokedata_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: PokeData_mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: m7tPnE6dB5TQxYCW
    ports:
      - 27945:1433

  pokedata_api:
    build:
      context: ./backend
      dockerfile: /src/PokeData/Dockerfile
    image: pokedata_api
    container_name: PokeData_api
    depends_on:
      - pokedata_mssql
    restart: unless-stopped
    environment:
      ASPNETCORE_Environment: Development
      Cors:AllowedOrigins:0: http://localhost:43044
      SQLCONNSTR_Master: Server=pokedata_mssql;Database=Pokemon;User Id=SA;Password=m7tPnE6dB5TQxYCW;Persist Security Info=False;Encrypt=False;
    ports:
      - 43551:8080

  pokedata_app:
    build:
      context: ./frontend
    image: pokedata_app
    container_name: PokeData_app
    depends_on:
      - pokedata_api
    restart: unless-stopped
    ports:
      - 43044:80
