name: Build PokéData Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    name: Build PokéData Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install
        # uses: borales/actions-yarn@v4
        # with:
        #   cmd: --cwd frontend install

      - name: Build for Production
        run: yarn build
        # uses: borales/actions-yarn@v4
        # with:
        #   cmd: --cwd frontend build

      - name: Run Tests & Coverage
        run: yarn test
        # uses: borales/actions-yarn@v4
        # with:
        #   cmd: --cwd frontend test
