name: Build PokéData Solution

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build PokéData Solution
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: actions/checkout@v4
        run: docker build . -t francispion.azurecr.io/pokedata:${{ github.sha }} -f src/PokeData/Dockerfile
